server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/52market?allowpublickeyretrieval=true&usessl=false&serverTimezone=UTC
    username: eddi
    password: eddi@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-circular-references: true

  jpa:
    open-in-view: false
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 1f6ab7138670a91099012c0341d8fe60
            redirect-uri: http://localhost:7777/oauth2/callback/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao

          google:
            client-id: 224711642600-k3gonf7fbvjj9m3rb7ffk0f7rlj74vla.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
            redirect-uri: http://localhost:7777/oauth2/callback/google

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


#   kafka:
#     consumer:
#       bootstrap-servers: localhost:9092
#       auto-offset-reset: earliest
#       key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#       value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#     producer:
#       bootstrap-servers: localhost:9092
#       key-serializer: org.apache.kafka.common.serialization.StringSerializer
#       value-serializer: org.apache.kafka.common.serialization.StringSerializer

